
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\admin\Desktop\oscar purea\Tendencias\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("480x260")
window.configure(bg = "#222831")


canvas = Canvas(
    window,
    bg = "#222831",
    height = 260,
    width = 480,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    480.0,
    260.0,
    fill="#222831",
    outline="")

canvas.create_text(
    102.0,
    6.0,
    anchor="nw",
    text="Actualización  de Datos",
    fill="#EEEEEE",
    font=("Jersey15 Regular", 32 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=202.0,
    y=213.0,
    width=76.0,
    height=18.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    101.0,
    96.79629516601562,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EEEEEE",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=41.0,
    y=90.29629516601562,
    width=120.0,
    height=11.0
)

canvas.create_rectangle(
    41.370361328125,
    82.0,
    143.59945678710938,
    88.29629611968994,
    fill="#000000",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=149.0,
    y=91.29629516601562,
    width=11.0,
    height=11.0
)

canvas.create_rectangle(
    43.0,
    94.04629516601562,
    102.0,
    99.54629516601562,
    fill="#000000",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    379.0,
    96.79629516601562,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EEEEEE",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=319.0,
    y=90.29629516601562,
    width=120.0,
    height=11.0
)

canvas.create_rectangle(
    319.370361328125,
    82.0,
    381.9607849121094,
    88.29629611968994,
    fill="#000000",
    outline="")

canvas.create_text(
    202.0,
    213.0,
    anchor="nw",
    text="Actualizar",
    fill="#222831",
    font=("Jersey15 Regular", 10 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=427.0,
    y=91.29629516601562,
    width=11.0,
    height=11.0
)

canvas.create_rectangle(
    321.0,
    94.04629516601562,
    380.0,
    99.54629516601562,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
